name: Deploy Next.js

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Setup pnpm
        run: |
          source ~/.nvm/nvm.sh
          npm install -g pnpm

      - name: Install Dependencies
        run: |
          source ~/.nvm/nvm.sh
          pnpm install --frozen-lockfile

      - name: Build Next.js
        run: |
          source ~/.nvm/nvm.sh
          pnpm run build
        env:
          NEXT_PUBLIC_API_URL: https://api.ctspk.com
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Restart PM2
        run: |
          source ~/.nvm/nvm.sh
          pm2 describe next-app > /dev/null 2>&1 \
            && pm2 restart next-app \
            || pm2 start "pnpm start -p 3001" --name "next-app"
